import type { CareerPath, EducationLevel } from "./types";

const DEMO_SOURCE =
  "Estimación demostrativa del prototipo académico RutaMX. No proviene de INEGI, IMSS ni de una bolsa de trabajo en vivo.";

function education(
  values: Partial<Record<EducationLevel, number>>,
): Record<EducationLevel, number> {
  return {
    Secundaria: 1,
    "Preparatoria incompleta": 2,
    "Preparatoria terminada": 3,
    "Universidad incompleta": 3,
    "Carrera técnica": 3,
    Otro: 2,
    ...values,
  };
}

export const CAREER_PATHS: CareerPath[] = [
  {
    id: "auxiliar-logistica",
    title: "Auxiliar de logística",
    category: "Logística",
    compatibleInterests: ["Logística", "Trabajo práctico", "Administración"],
    relevantSkills: [
      "organizacion",
      "inventario",
      "excel",
      "paqueteria",
      "reparto",
      "almacen",
      "puntualidad",
      "orden",
    ],
    salaryMin: 7500,
    salaryMax: 11500,
    preparationTime: "2 a 6 semanas",
    skillsRequired: [
      "Registro básico de entradas y salidas",
      "Comunicación clara con el equipo",
      "Uso inicial de hojas de cálculo",
    ],
    suggestedNextStep:
      "Arma un CV de una página destacando cualquier experiencia con pedidos, inventario o entregas, aunque haya sido informal.",
    confidence: "Media",
    dataYear: 2026,
    sourceLabel: DEMO_SOURCE,
    educationFit: education({
      Secundaria: 4,
      "Preparatoria incompleta": 4,
      "Preparatoria terminada": 4,
      "Carrera técnica": 3,
    }),
    plan: {
      thisWeek: [
        "Lista 5 tareas que ya hayas hecho: recibir mercancía, acomodar cajas, anotar pedidos o coordinar entregas.",
        "Busca 3 vacantes de auxiliar de almacén o logística en tu estado y anota qué piden en común.",
      ],
      next30Days: [
        "Practica Excel básico: tablas, filtros y una lista de inventario ficticia.",
        "Pide una carta o referencia a alguien con quien hayas colaborado, aunque sea en un negocio familiar.",
      ],
      whenReady: [
        "Postula a roles de auxiliar, no a jefaturas. Destaca puntualidad y manejo de inventario.",
        "En la entrevista, cuenta un ejemplo concreto de cómo evitaste un error o aceleraste una entrega.",
      ],
    },
  },
  {
    id: "soporte-tecnico",
    title: "Soporte técnico",
    category: "Tecnología",
    compatibleInterests: ["Tecnología", "Servicio al cliente", "Trabajo práctico"],
    relevantSkills: [
      "computadora",
      "windows",
      "celular",
      "redes",
      "wifi",
      "impresora",
      "instalacion",
      "software",
      "pacencia",
      "paciencia",
    ],
    salaryMin: 8500,
    salaryMax: 14000,
    preparationTime: "4 a 10 semanas",
    skillsRequired: [
      "Diagnóstico básico de hardware y software",
      "Explicar soluciones en lenguaje sencillo",
      "Documentar tickets o incidencias",
    ],
    suggestedNextStep:
      "Completa un curso introductorio gratuito de soporte TI y practica resolviendo fallas comunes en Windows y Android.",
    confidence: "Media",
    dataYear: 2026,
    sourceLabel: DEMO_SOURCE,
    educationFit: education({
      "Carrera técnica": 5,
      "Preparatoria terminada": 4,
      "Universidad incompleta": 4,
      "Preparatoria incompleta": 3,
    }),
    plan: {
      thisWeek: [
        "Anota 8 problemas técnicos que ya hayas resuelto (Wi-Fi, celular, impresora, cuentas).",
        "Crea un perfil sencillo describiendo que ayudas a personas a usar tecnología.",
      ],
      next30Days: [
        "Estudia fundamentos de hardware, redes domésticas y atención al usuario.",
        "Practica explicar una falla y su solución en menos de un minuto.",
      ],
      whenReady: [
        "Busca vacantes de mesa de ayuda, soporte N1 o técnico de campo junior.",
        "Lleva ejemplos de cómo calmaste a alguien y resolviste el problema paso a paso.",
      ],
    },
  },
  {
    id: "ejecutivo-ventas",
    title: "Ejecutivo de ventas",
    category: "Ventas",
    compatibleInterests: ["Ventas", "Servicio al cliente", "Marketing"],
    relevantSkills: [
      "ventas",
      "persuasion",
      "comunicacion",
      "whatsapp",
      "clientes",
      "mostrador",
      "comision",
      "negociacion",
    ],
    salaryMin: 8000,
    salaryMax: 16000,
    preparationTime: "1 a 4 semanas",
    skillsRequired: [
      "Escuchar la necesidad del cliente",
      "Seguimiento por WhatsApp o llamadas",
      "Registro simple de prospectos",
    ],
    suggestedNextStep:
      "Prepara 3 historias cortas de cuando convenciste a alguien de comprar, contratar o probar un producto.",
    confidence: "Baja",
    dataYear: 2026,
    sourceLabel: DEMO_SOURCE,
    educationFit: education({
      Secundaria: 3,
      "Preparatoria incompleta": 4,
      "Preparatoria terminada": 4,
      Otro: 3,
    }),
    plan: {
      thisWeek: [
        "Escribe qué vendiste o recomendaste alguna vez: comida, ropa, recargas, servicios.",
        "Practica un saludo de 20 segundos y una pregunta para entender qué necesita la otra persona.",
      ],
      next30Days: [
        "Aprende a anotar contactos y dar seguimiento al día siguiente.",
        "Observa cómo cierran una venta en un comercio local y copia las frases útiles.",
      ],
      whenReady: [
        "Postula a ventas de piso, telemarketing o ejecutivo junior. Pregunta cómo se paga la comisión.",
        "En la entrevista, cuantifica: cuántas personas atendiste o qué meta lograste, aunque sea aproximada.",
      ],
    },
  },
  {
    id: "atencion-cliente",
    title: "Atención al cliente",
    category: "Servicio",
    compatibleInterests: ["Servicio al cliente", "Ventas", "Administración"],
    relevantSkills: [
      "atencion",
      "clientes",
      "escucha",
      "telefono",
      "whatsapp",
      "pacencia",
      "paciencia",
      "quejas",
      "amable",
    ],
    salaryMin: 7500,
    salaryMax: 12000,
    preparationTime: "1 a 3 semanas",
    skillsRequired: [
      "Trato respetuoso bajo presión",
      "Seguir un guion o protocolo",
      "Registrar casos en un sistema sencillo",
    ],
    suggestedNextStep:
      "Redacta un CV destacando trato con público, resolución de quejas y uso de WhatsApp o teléfono.",
    confidence: "Media",
    dataYear: 2026,
    sourceLabel: DEMO_SOURCE,
    educationFit: education({
      Secundaria: 4,
      "Preparatoria incompleta": 4,
      "Preparatoria terminada": 4,
    }),
    plan: {
      thisWeek: [
        "Lista situaciones en las que ayudaste a alguien molesto y cómo lo resolviste.",
        "Grábate respondiendo con calma a una queja ficticia de 30 segundos.",
      ],
      next30Days: [
        "Practica escribir respuestas claras por chat: saludo, solución, cierre.",
        "Familiarízate con horarios rotativos; muchas vacantes los piden.",
      ],
      whenReady: [
        "Busca call center, mostrador, hostess o chat de soporte en tu ciudad o en remoto.",
        "Pregunta por capacitación inicial; es común y reduce la barrera de entrada.",
      ],
    },
  },
  {
    id: "auxiliar-administrativo",
    title: "Auxiliar administrativo",
    category: "Administración",
    compatibleInterests: ["Administración", "Finanzas", "Logística"],
    relevantSkills: [
      "office",
      "excel",
      "word",
      "archivos",
      "agenda",
      "correo",
      "organizacion",
      "tramites",
      "facturas",
    ],
    salaryMin: 8000,
    salaryMax: 12500,
    preparationTime: "3 a 8 semanas",
    skillsRequired: [
      "Orden de documentos y agenda",
      "Paquetería Office a nivel básico",
      "Comunicación escrita formal",
    ],
    suggestedNextStep:
      "Prepara una carpeta digital de ejemplo: lista de pendientes, calendario y un correo formal.",
    confidence: "Media",
    dataYear: 2026,
    sourceLabel: DEMO_SOURCE,
    educationFit: education({
      "Preparatoria terminada": 5,
      "Universidad incompleta": 5,
      "Carrera técnica": 4,
      "Preparatoria incompleta": 3,
    }),
    plan: {
      thisWeek: [
        "Organiza tus documentos personales en carpetas: identificación, constancias, referencias.",
        "Redacta un correo formal de solicitud de empleo y pídele a alguien que lo revise.",
      ],
      next30Days: [
        "Practica Excel: SUMAR, filtros y un directorio de contactos.",
        "Aprende vocabulario de oficina: oficios, facturas, altas, bitácora.",
      ],
      whenReady: [
        "Postula a auxiliar, recepcionista administrativo o apoyo de oficina.",
        "Lleva un ejemplo de tabla u orden que hayas creado, aunque sea de un negocio familiar.",
      ],
    },
  },
  {
    id: "operador-almacen",
    title: "Operador de almacén",
    category: "Logística",
    compatibleInterests: ["Logística", "Trabajo práctico"],
    relevantSkills: [
      "carga",
      "almacen",
      "fisico",
      "inventario",
      "montacargas",
      "empaque",
      "reparto",
      "fuerza",
    ],
    salaryMin: 7200,
    salaryMax: 11000,
    preparationTime: "1 a 3 semanas",
    skillsRequired: [
      "Trabajo físico con normas básicas de seguridad",
      "Seguir órdenes de surtido",
      "Conteo y etiquetado",
    ],
    suggestedNextStep:
      "Identifica vacantes de almacén, picking o paquetería cerca de tu zona y revisa turnos y requisitos de seguridad.",
    confidence: "Media",
    dataYear: 2026,
    sourceLabel: DEMO_SOURCE,
    educationFit: education({
      Secundaria: 5,
      "Preparatoria incompleta": 5,
      "Preparatoria terminada": 4,
      Otro: 4,
    }),
    plan: {
      thisWeek: [
        "Confirma que puedes cubrir turnos y traslado al polígono o centro de distribución más cercano.",
        "Anota si tienes experiencia cargando, empacando o acomodando mercancía.",
      ],
      next30Days: [
        "Aprende términos: picking, packing, SKU, merma.",
        "Si hay opción, investiga un curso corto de seguridad en almacén o montacargas.",
      ],
      whenReady: [
        "Lleva identificaciones y disponibilidad inmediata; el proceso suele ser rápido.",
        "Pregunta por equipo de seguridad y si pagan tiempo extra de forma clara.",
      ],
    },
  },
  {
    id: "tecnico-mantenimiento",
    title: "Técnico de mantenimiento",
    category: "Oficios",
    compatibleInterests: ["Trabajo práctico", "Tecnología"],
    relevantSkills: [
      "herramientas",
      "electricidad",
      "plomeria",
      "reparacion",
      "mantenimiento",
      "aire",
      "motores",
      "soldadura",
    ],
    salaryMin: 9000,
    salaryMax: 15500,
    preparationTime: "6 a 12 semanas",
    skillsRequired: [
      "Uso seguro de herramientas",
      "Diagnóstico básico de fallas",
      "Lectura de instrucciones técnicas",
    ],
    suggestedNextStep:
      "Documenta reparaciones que ya hayas hecho en casa, taller o negocio y busca un curso técnico corto en tu localidad.",
    confidence: "Baja",
    dataYear: 2026,
    sourceLabel: DEMO_SOURCE,
    educationFit: education({
      "Carrera técnica": 5,
      Secundaria: 3,
      "Preparatoria incompleta": 3,
      "Preparatoria terminada": 4,
    }),
    plan: {
      thisWeek: [
        "Fotografía (sin datos personales) o describe 3 reparaciones que hayas resuelto.",
        "Revisa oficios demandados cerca: eléctrico, A/C, mecánica ligera, mantenimiento predial.",
      ],
      next30Days: [
        "Inscríbete a un módulo corto de seguridad eléctrica o mantenimiento general.",
        "Aprende a cotizar materiales y tiempo de una reparación sencilla.",
      ],
      whenReady: [
        "Postula a auxiliar de mantenimiento, no a técnico senior, si aún no tienes certificado.",
        "Ofrece disponibilidad para turnos y menciona herramientas propias solo si las tienes.",
      ],
    },
  },
  {
    id: "marketing-digital-junior",
    title: "Marketing digital junior",
    category: "Marketing",
    compatibleInterests: ["Marketing", "Tecnología", "Ventas"],
    relevantSkills: [
      "redes",
      "instagram",
      "tiktok",
      "canva",
      "diseno",
      "contenido",
      "copy",
      "facebook",
      "publicidad",
    ],
    salaryMin: 8000,
    salaryMax: 14000,
    preparationTime: "4 a 10 semanas",
    skillsRequired: [
      "Crear contenido simple para redes",
      "Canva u otra herramienta visual básica",
      "Medir likes, alcance o mensajes, sin ser experto",
    ],
    suggestedNextStep:
      "Arma 6 piezas de contenido de ejemplo para un negocio local ficticio y explícalas en un PDF de una página.",
    confidence: "Baja",
    dataYear: 2026,
    sourceLabel: DEMO_SOURCE,
    educationFit: education({
      "Universidad incompleta": 5,
      "Preparatoria terminada": 4,
      "Carrera técnica": 3,
      "Preparatoria incompleta": 2,
    }),
    plan: {
      thisWeek: [
        "Elige un negocio de tu colonia y propone 3 ideas de publicación que sí haría la gente.",
        "Abre Canva y replica el estilo de 2 marcas que te gusten, sin copiar logos protegidos.",
      ],
      next30Days: [
        "Aprende métricas básicas: alcance, clics, mensajes. No necesitas ads avanzados aún.",
        "Ofrece ayudar una semana a un comercio a cambio de una referencia escrita.",
      ],
      whenReady: [
        "Postula a community junior, auxiliar de marketing o freelance de contenidos.",
        "Muestra el PDF de ejemplos; vale más que un título incompleto para este rol de entrada.",
      ],
    },
  },
  {
    id: "auxiliar-contable",
    title: "Auxiliar contable",
    category: "Finanzas",
    compatibleInterests: ["Finanzas", "Administración"],
    relevantSkills: [
      "numeros",
      "excel",
      "facturas",
      "contabilidad",
      "sat",
      "cobranza",
      "gastos",
      "caja",
    ],
    salaryMin: 8500,
    salaryMax: 13500,
    preparationTime: "6 a 12 semanas",
    skillsRequired: [
      "Orden de facturas y gastos",
      "Excel básico-intermedio",
      "Vocabulario de CFDI e IVA a nivel introductorio",
    ],
    suggestedNextStep:
      "Toma un curso introductorio de auxiliar contable y practica una bitácora de ingresos y egresos.",
    confidence: "Media",
    dataYear: 2026,
    sourceLabel: DEMO_SOURCE,
    educationFit: education({
      "Universidad incompleta": 5,
      "Carrera técnica": 5,
      "Preparatoria terminada": 3,
      "Preparatoria incompleta": 2,
    }),
    plan: {
      thisWeek: [
        "Haz una tabla de tus propios gastos de 7 días: fecha, concepto, monto.",
        "Identifica si te atrae más caja, facturación o apoyo a un despacho.",
      ],
      next30Days: [
        "Estudia qué es un CFDI y para qué sirve un auxiliar, sin pretender ser contador.",
        "Practica Excel: SUMAR.SI y una conciliación simple de 10 movimientos.",
      ],
      whenReady: [
        "Busca auxiliar contable, auxiliar de cobranza o apoyo fiscal en despachos pequeños.",
        "Aclara que buscas un rol de entrada con supervisión; eso aumenta tus chances.",
      ],
    },
  },
  {
    id: "recepcionista",
    title: "Recepcionista",
    category: "Servicio",
    compatibleInterests: ["Servicio al cliente", "Administración"],
    relevantSkills: [
      "recepcion",
      "agenda",
      "telefono",
      "presentacion",
      "office",
      "citas",
      "visitantes",
      "amable",
    ],
    salaryMin: 7200,
    salaryMax: 11000,
    preparationTime: "1 a 4 semanas",
    skillsRequired: [
      "Imagen profesional y puntualidad",
      "Agenda de citas y recados",
      "Atención presencial y telefónica",
    ],
    suggestedNextStep:
      "Prepara un saludo estándar, practica tomar recados y actualiza un CV con foto opcional según la vacante.",
    confidence: "Media",
    dataYear: 2026,
    sourceLabel: DEMO_SOURCE,
    educationFit: education({
      "Preparatoria terminada": 5,
      "Preparatoria incompleta": 4,
      Secundaria: 3,
      "Universidad incompleta": 4,
    }),
    plan: {
      thisWeek: [
        "Practica un saludo de recepción y cómo transferir una llamada.",
        "Revisa vestimenta y puntualidad; en este rol pesan tanto como el Excel.",
      ],
      next30Days: [
        "Aprende a usar un calendario compartido (Google Calendar es suficiente).",
        "Redacta mensajes cortos para confirmar citas.",
      ],
      whenReady: [
        "Postula en clínicas, oficinas, hoteles pequeños o escuelas.",
        "Pregunta horario de comida y si hay caja; algunos puestos mezclan recepción y cobro.",
      ],
    },
  },
  {
    id: "asistente-ecommerce",
    title: "Asistente de e-commerce",
    category: "Comercio digital",
    compatibleInterests: ["Marketing", "Logística", "Tecnología", "Ventas"],
    relevantSkills: [
      "tienda",
      "online",
      "pedidos",
      "mercadolibre",
      "amazon",
      "fotos",
      "inventario",
      "whatsapp",
      "envios",
    ],
    salaryMin: 8000,
    salaryMax: 13000,
    preparationTime: "3 a 8 semanas",
    skillsRequired: [
      "Publicar o actualizar productos",
      "Seguimiento de pedidos y envíos",
      "Atención por chat",
    ],
    suggestedNextStep:
      "Crea 5 fichas de producto de ejemplo (título, precio, foto y política de envío ficticia).",
    confidence: "Baja",
    dataYear: 2026,
    sourceLabel: DEMO_SOURCE,
    educationFit: education({
      "Preparatoria terminada": 4,
      "Universidad incompleta": 5,
      "Carrera técnica": 3,
      "Preparatoria incompleta": 3,
    }),
    plan: {
      thisWeek: [
        "Navega 10 publicaciones de Mercado Libre y anota qué las hace claras o confusas.",
        "Si ya vendiste por redes, documenta el proceso: foto, mensaje, pago, envío.",
      ],
      next30Days: [
        "Aprende a redactar títulos y responder preguntas frecuentes de envío.",
        "Practica una hoja de pedidos: cliente, producto, estatus, guía.",
      ],
      whenReady: [
        "Busca asistente de tienda en línea, marketplace o community con ventas.",
        "Muestra tus 5 fichas de ejemplo; demuestran que entiendes el flujo, no solo las redes.",
      ],
    },
  },
  {
    id: "capturista-datos",
    title: "Capturista de datos",
    category: "Administración",
    compatibleInterests: ["Administración", "Tecnología", "Finanzas"],
    relevantSkills: [
      "teclado",
      "excel",
      "datos",
      "precision",
      "office",
      "escritura",
      "concentrado",
      "archivos",
    ],
    salaryMin: 7000,
    salaryMax: 10500,
    preparationTime: "1 a 4 semanas",
    skillsRequired: [
      "Velocidad y precisión al teclear",
      "Excel o Google Sheets básico",
      "Concentración en tareas repetitivas",
    ],
    suggestedNextStep:
      "Mide cuántas líneas puedes capturar con pocos errores y menciona esa disciplina en tu CV.",
    confidence: "Media",
    dataYear: 2026,
    sourceLabel: DEMO_SOURCE,
    educationFit: education({
      Secundaria: 4,
      "Preparatoria incompleta": 4,
      "Preparatoria terminada": 4,
      "Universidad incompleta": 3,
    }),
    plan: {
      thisWeek: [
        "Practica 20 minutos diarios de captura en una hoja: nombres, fechas, montos.",
        "Activa un corrector y aprende atajos: copiar, pegar, buscar.",
      ],
      next30Days: [
        "Mejora velocidad sin sacrificar exactitud; anota tu avance.",
        "Familiarízate con formatos CSV y cómo no romper columnas.",
      ],
      whenReady: [
        "Postula a captura, digitalización o apoyo de padrones. Muchos son presenciales.",
        "Enfatiza confidencialidad: no compartes información de terceros.",
      ],
    },
  },
];
